### ISSUE TITLE
Opera browser proxy (VPN) support

### ISSUE THREAD

**Issue by unixfox** [DeltaEvo/proxy-scraper#4]
The Opera browser has a proxy feature (called a VPN in their product) and it's possible to connect to without using their browser.
It provides 5 regions and each time we connect to a region the IP isn't the same so it's pretty cool because their proxy aren't blocked by google, quick and aren't rate limited.

A project is available here for getting the IP of the proxy: https://github.com/nampud/oprah-proxy
Credentials:
- client_type (pick one) : 
  * `se0316`
  * `se0310`
  * `se0306`
  * `se0311`
  * `se0312` (credentials from [official Opera VPN android app](https://play.google.com/store/apps/details?id=com.opera.vpn))
- client_key :
  * `94938A583190AF928BC4FA2279DC10AE8FABB5E9E21826C9092B404D24B949A0`
  * `AE4CA57D1E3C0E6711C53416BFA0988F08D41B428D26D053A4C46EC72A79B9E7` 
  * `7502E43F3381C82E571733A350099BB5D449DD48311839C099ADC4631BA0CC04`
  * `95d5e2cbcfd8d0c436d87c198dde01fb62766a1f`
  * `2D67631A124F7AE10629ACA9ACA5AB21D67D30BDF6CF11C0B78735527FDF4DCA`

Additional documentation:
- Original project: https://github.com/spaze/oprah-proxy
- Discussions about the API:
  * https://github.com/spaze/oprah-proxy/issues/21
  * https://github.com/spaze/oprah-proxy/issues/3
- **Everytime we connect to the proxy it's another random IP address that it's served so one proxy could have more than 50 public IP because the record A for the hostname (ex: nl.opera-proxy.net) is continuously updated: https://mxtoolbox.com/SuperTool.aspx?action=a%3anl.opera-proxy.net&run=toolpage#**
- **These are only https proxy.**

**Comment by kekukui** [comment]
The script generates credentials for the encrypted proxy which can be used with other apps that support a proxy configuration.  There is also a browser GUI for Firefox to change the proxy configuration using a toolbar button:

https://addons.mozilla.org/en-US/firefox/addon/pac-reloader/

But it seems the real Opera browser generates a new user/password for each proxy server change.  To accomplish the same in other browsers you need to use that script in a browser extension.

**Comment by hbakhtiyor** [comment]
@unixfox none of the client's types/keys work

**Comment by unixfox** [comment]
Doesn't really work anymore: https://github.com/nampud/oprah-proxy/issues/6
